spring:
  application:
    name: vibe-music-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://YOUR_MYSQL_HOST:3306/vibe_music?useUnicode=true&characterEncoding=utf-8&useSSL=false # 修改你的 MySQL 地址和库名
    username: YOUR_MYSQL_USER
    password: YOUR_MYSQL_PASSWORD
    type: com.alibaba.druid.pool.DruidDataSource # 配置连接池